# Generated by Django 4.2 on 2024-09-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntasendMpesaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=100)),
                ("transaction_id", models.CharField(max_length=500)),
                ("invoice_id", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255, null=True)),
                (
                    "charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("api_ref", models.CharField(max_length=255, null=True)),
                ("currency", models.CharField(max_length=255, null=True)),
                ("state", models.CharField(max_length=255)),
                ("mpesa_reference", models.CharField(max_length=255, null=True)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=100)),
                ("phone_number", models.CharField(max_length=255)),
                ("customer", models.JSONField(default=dict)),
                ("transaction_timestamp", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
