# Generated by Django 4.2 on 2024-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intasend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intasendmpesadata",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
