# Generated by Django 4.2 on 2024-09-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intasend", "0002_intasendmpesadata_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="intasendmpesadata",
            name="amount_transacted",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
