# Generated by Django 4.2 on 2024-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intasend", "0004_alter_intasendmpesadata_net_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntasendPaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("payment_link_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("is_active", models.BooleanField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("usage_limit", models.IntegerField()),
                ("qrcode", models.URLField()),
                ("url", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=255)),
                ("mobile_tarrif", models.CharField(max_length=255)),
                ("card_tarrif", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
