# Generated by Django 4.2 on 2024-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intasend", "0006_intasendpaymentlink_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="intasendpaymentlink",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
